### ISSUE TITLE
Some Feedback, Week 03 (W48-Nov30)

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/DM_CS_WS_2016-17#12]
## Terrorism Dataset

* I would not bother with enumerating the sections, # ## and ### without numbers may suffice

* It's actually more important to enumerate the figures & tables

* Fig. 1.3 -- can we normalize by number of attacks ?

* Now even epic music in the videos?? This is going to be an interesting semester

* "In this Youtube Link it is possible to see a clear analysis" this is very vague. Rather do not put it. What clear analysis? State / summarize what we see in the video.
  * I would it write such like: "The most popular targets per country are the following (Fig. X)" ... and make the figure a clickable link to the youtube video, as in: 

[![ScreenShot](http://img.youtube.com/vi/UvEiSa6_EPA/0.jpg)](https://www.youtube.com/watch?v=UvEiSa6_EPA)

* Stil that list of countries - target is too much info for me to digest. So... what should I learn and take home from all this points? **What's most important?**

* Again, avoid these "In this Youtube Link it is possible to see a clear analysis", and summarize way more your findings.

* "We found that the Hijacking and Kidnapping events are interesting because it may help predict behavior in ongoing situations, especially when the perpetrators are open to negotiations." ? Too vague, and ofc, that's the whole point of hijacking / kidnapping

* Avoid the boring "In the figure below we can see the number of kidnapping or hijacking related events occurring every year." -- Just use a caption for the figure and state "Number of kidnapping ..." --> Simple

* ... similar for feedback for the rest

## Google

* NaW (Not-a-Word) words :P -- Maybe NaW terms ?

* Great, put the link of your scripts in your home dataset page please (if not already there): https://github.com/brosequartz/GoogleNGramDataset

* Good that you put the character names as stopwords -- On the other hand, I guess there are also peoples names in the google datasets, so maybe not so good ?

* Can you point to the exact file or python script where you have your latest list of stopwords?

* Link of the English dictionary missing?

* "Frequency cleaning" examples of those? Examples of NaWs ?

* Note that your normalization has a different meaning than for example normalizing the total number of thou's in 1963 divided by the total number of all words in 1963. Not that it's wrong, just that you must be aware of this.

  * From this construct, we likely encounter the case that the numbers for "thy"  or "thou" are actually way higher than for "would" -- doesn't this come as a surprise to you? -- Because of your construct, the frequency between numbers are not directly comparable.

* I'm very surprised that "man" declines in usage. Can you display again now normalizing by total number of words (yes, bear in mind that now you will have very low probabilities for each word, though I guess still greater than zero).

## UK RE

* Just personally very curious: the other day I watched a documentary about the rich in London that, because they cannot expand their properties any other way, the expand below ground: they build mansion-like basements. And of course the prices are huge. Can you spot any of this behavior in the data?

* Housing type numbers: seems like a zipf distribution. Can you show it as a sorted histogram ?

* Is there a way to make the figures bigger on the wiki too? Maybe put a link to the original images?

* Are you saying that the average price of properties for some agents is 100 pounds? (!?) What are they selling?

* "rental price per month according to the number of bedrooms" this may not tell us much, since it seems (?) that the properties with very high number of bedrooms are either exceptions or otherwise of course very expensive. There may not be many numbers for the 10s, 9s, 12s bedrooms, so that's why they may not be sorted (that is, exceptions have a high weight)

* More interesting: normalize the price by the number of bedrooms --> does it get cheaper for very big families or the other way around?

* "London is an expensive city to live compared to Munich" --> can you show in a map visualization the disparity of prices between London and Munich ?

* Could you highlight W1 and SE06 or other interesting areas on the map ?

* "However a lot of the top repeated descriptions were very similar (as in same descriptions with slight changes such as agent name)" -- maybe you can apply levenshtein distance or similar and put a threshold

* Overall, nice exploration of your data and concise description of your findings

**Comment by ImkeHelene** [comment]
Dear @juanmirocks,

thanks for your feedback. We have a couple of questions / remarks below.
One other question: Were we supposed to post a wiki entry this week since there is no class?

NaW (Not-a-Word) words :P -- Maybe NaW terms ?
---> will change that
* Great, put the link of your scripts in your home dataset page please (if not already there): https://github.com/brosequartz/GoogleNGramDataset

--> Will do that

* Good that you put the character names as stopwords -- On the other hand, I guess there are also peoples names in the google datasets, so maybe not so good ?

---> We do not want to investigate names (we do not regard them as interesting) so for our purposes they are not needed.

* Can you point to the exact file or python script where you have your latest list of stopwords?

----> it will be in Cleaning.py but we are currently still working on that script.

* Link of the English dictionary missing?
---> Should be on the wiki-page of week 3 (was put there last wednesday).

* "Frequency cleaning" examples of those? Examples of NaWs ?
---> Frequency: For each table the threshold depends on the size and the highest counts. This week we were thinking about using : highest count / # of rows
---> NaW: e.g. Abbreviations, Words without vowls (vowls also include y, w). After doing some research we found out that there are basically only sound words (like tsktsk) without a, e, i, o, u, y, w in the english language.

* Note that your normalization has a different meaning than for example normalizing the total number of thou's in 1963 divided by the total number of all words in 1963. Not that it's wrong, just that you must be aware of this.

--->We do not do that. We only divide by the volume counts of the same line.

  * From this construct, we likely encounter the case that the numbers for "thy"  or "thou" are actually way higher than for "would" -- doesn't this come as a surprise to you? -- Because of your construct, the frequency between numbers are not directly comparable.

--> As was explained mulitple times during the last 3 presentations we want to handle those words separately. 

* I'm very surprised that "man" declines in usage. Can you display again now normalizing by total number of words (yes, bear in mind that now you will have very low probabilities for each word, though I guess still greater than zero).
---> We do not quite understand what to do. Would you like a plot of total_count/ # of all words in Google unigrams? Or total_count / # of all words starting with a m of Google? Or what do you mean by total number of words?

Regards,
@brosequartz , Imke

**Comment by juanmirocks** [comment]
Dear all. I could not answer before in case you had questions. Sorry. See
you tomorrow.
