### ISSUE TITLE
Permission Denied on the server

### ISSUE THREAD

**Issue by ssoima** [Rostlab/DM_CS_WS_2016-17#16]
Hi @juanmirocks @T1mK ,

we get a "Permission Denied" when we want to connect to the server. Do you know why?

Kind regards,
Sergiu (Crimes UK team)

**Comment by ImkeHelene** [comment]
Hi @juanmirocks,
I am having the same issue since last week. 

Kind regards,
Imke

**Comment by T1mK** [comment]
Hi All,

Thanks for the notifications. You all should be able to log in now. 

The problem arose from the server being out of memory. Once memory is gone, the OS tries to free some by killing processes. Eventually, it kills processes that are needed in order to log in to the system.

Please don’t be a memory hog, and monitor your memory usage. There are programs like ‘top’ and ‘htop’ which assist with this.

Cheers,
Tim

**Comment by juanmirocks** [comment]
Thanks all, sorry for the complication, please report if solved
